SELECT
	TABLE_NAME AS [Name],
	CONCAT(TABLE_CATALOG, ',', TABLE_SCHEMA) AS [ArtifactNamespace],
	COLUMN_NAME AS [Schema.Name],
	CASE
		WHEN RIGHT(DATA_TYPE, 4) IN ('char', 'text') THEN FORMATMESSAGE('%s(%i)', DATA_TYPE, CHARACTER_MAXIMUM_LENGTH)
		WHEN DATA_TYPE IN ('decimal', 'numeric') THEN FORMATMESSAGE('%s(%i,%i)', DATA_TYPE, NUMERIC_PRECISION, NUMERIC_SCALE)
		WHEN DATA_TYPE LIKE '%binary' THEN FORMATMESSAGE('%s(%s)', DATA_TYPE, CASE WHEN CHARACTER_MAXIMUM_LENGTH = -1 THEN 'MAX' ELSE CONVERT(VARCHAR(10), CHARACTER_MAXIMUM_LENGTH) END)
		ELSE DATA_TYPE
	END AS [Schema.DataType],
	TABLE_SCHEMA AS [DataSource.Schema]
FROM
	INFORMATION_SCHEMA.COLUMNS
ORDER BY
	TABLE_SCHEMA,
	TABLE_NAME,
	ORDINAL_POSITION