//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLHBuilder.Components.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DLHBuilder.Components.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AttributeKeyDisabled_16x {
            get {
                object obj = ResourceManager.GetObject("AttributeKeyDisabled_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AttributeRelationshipEditor_16x {
            get {
                object obj = ResourceManager.GetObject("AttributeRelationshipEditor_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AttributeWithDisabledHierarchy_16x {
            get {
                object obj = ResourceManager.GetObject("AttributeWithDisabledHierarchy_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Column_16x {
            get {
                object obj = ResourceManager.GetObject("Column_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Copy_16x {
            get {
                object obj = ResourceManager.GetObject("Copy_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DatabaseApplication_16x {
            get {
                object obj = ResourceManager.GetObject("DatabaseApplication_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DatabaseStoredProcedures_16x {
            get {
                object obj = ResourceManager.GetObject("DatabaseStoredProcedures_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    col.TABLE_SCHEMA,
        ///	col.TABLE_NAME, 
        ///    col.ORDINAL_POSITION,
        ///	col.COLUMN_NAME, 
        ///	DATA_TYPE 
        ///	+ 
        ///	CASE 
        ///		WHEN CHARACTER_MAXIMUM_LENGTH IS NOT NULL 
        ///			THEN &apos;(&apos; + CASE CHARACTER_MAXIMUM_LENGTH WHEN -1 THEN &apos;MAX&apos; ELSE CONVERT(VARCHAR(10), CHARACTER_MAXIMUM_LENGTH) END + &apos;)&apos;
        ///		ELSE &apos;&apos;
        ///	END
        ///	+
        ///	CASE 
        ///		WHEN NUMERIC_PRECISION IS NOT NULL AND DATA_TYPE IN (&apos;decimal&apos;, &apos;numeric&apos;)
        ///			THEN &apos;(&apos; + ISNULL(CONVERT(VARCHAR(10), NUMERIC_PRECISION), &apos;&apos;) + ISNULL(&apos;,&apos; + CONVERT(VARCHAR(10), NUMERIC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DatabaseTableColumns {
            get {
                return ResourceManager.GetString("DatabaseTableColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DataSourceReference_16x {
            get {
                object obj = ResourceManager.GetObject("DataSourceReference_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EnvironmentDefinition_16x {
            get {
                object obj = ResourceManager.GetObject("EnvironmentDefinition_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FolderBrowserDialogControl_16x {
            get {
                object obj = ResourceManager.GetObject("FolderBrowserDialogControl_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FolderClosed_16x {
            get {
                object obj = ResourceManager.GetObject("FolderClosed_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FolderOpened_16x {
            get {
                object obj = ResourceManager.GetObject("FolderOpened_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GroupByAccess_16x {
            get {
                object obj = ResourceManager.GetObject("GroupByAccess_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap KeyDown_16x {
            get {
                object obj = ResourceManager.GetObject("KeyDown_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Link_16x {
            get {
                object obj = ResourceManager.GetObject("Link_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OpenFile_16x {
            get {
                object obj = ResourceManager.GetObject("OpenFile_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Plugged_16x {
            get {
                object obj = ResourceManager.GetObject("Plugged_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ProjectFilterFile_16x {
            get {
                object obj = ResourceManager.GetObject("ProjectFilterFile_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Property_16x {
            get {
                object obj = ResourceManager.GetObject("Property_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PropertyKey_16x {
            get {
                object obj = ResourceManager.GetObject("PropertyKey_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PropertySnippet_16x {
            get {
                object obj = ResourceManager.GetObject("PropertySnippet_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RouteService_16x {
            get {
                object obj = ResourceManager.GetObject("RouteService_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Run_16x {
            get {
                object obj = ResourceManager.GetObject("Run_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Save_16x {
            get {
                object obj = ResourceManager.GetObject("Save_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ScriptGroup_16x {
            get {
                object obj = ResourceManager.GetObject("ScriptGroup_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SQL_16x {
            get {
                object obj = ResourceManager.GetObject("SQL_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	col.TABLE_NAME AS [Name],
        ///	CONCAT_WS(&apos;,&apos;, col.TABLE_CATALOG, &apos;Tables&apos;, col.TABLE_SCHEMA) AS [ArtifactNamespace],
        ///	col.COLUMN_NAME AS [Schema.Name],
        ///	CASE
        ///		WHEN RIGHT(col.DATA_TYPE, 4) IN (&apos;char&apos;, &apos;text&apos;) THEN FORMATMESSAGE(&apos;%s(%s)&apos;, col.DATA_TYPE,CASE WHEN col.CHARACTER_MAXIMUM_LENGTH = -1 THEN &apos;MAX&apos; ELSE CONVERT(VARCHAR(10), col.CHARACTER_MAXIMUM_LENGTH) END)
        ///		WHEN col.DATA_TYPE IN (&apos;decimal&apos;, &apos;numeric&apos;) THEN FORMATMESSAGE(&apos;%s(%i,%i)&apos;, col.DATA_TYPE, col.NUMERIC_PRECISION, col.NUMERIC_SCALE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQLArtifactImport {
            get {
                return ResourceManager.GetString("SQLArtifactImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	&apos;{0}&apos; AS [Name],
        ///	CONCAT_WS(&apos;,&apos;, DB_NAME(), &apos;Stored Procedures&apos;, OBJECT_SCHEMA_NAME(OBJECT_ID(&apos;{0}&apos;))) AS ArtifactNamespace,
        ///	name AS [Schema.Name],
        ///	system_type_name AS [Schema.DataType],
        ///	OBJECT_SCHEMA_NAME(OBJECT_ID(&apos;{0}&apos;)) AS [DataSource.Schema],
        ///	&apos;StoredProcedure&apos; AS [DataSource.ObjectType],
        ///	&apos;{0}&apos; AS [DataSource.ObjectName],
        ///	CONCAT_WS(&apos;.&apos;, DB_NAME(), OBJECT_SCHEMA_NAME(OBJECT_ID(&apos;{0}&apos;)), &apos;{0}&apos;) AS [DataSource.Name],
        ///	&apos;None&apos; AS [Schema.KeyType],
        ///	&apos;true&apos; AS [Schema.IsNullable],
        ///	CASE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQLArtifactImportStoredProcedure {
            get {
                return ResourceManager.GetString("SQLArtifactImportStoredProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SQLScript_16x {
            get {
                object obj = ResourceManager.GetObject("SQLScript_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SQLServerProject_16x {
            get {
                object obj = ResourceManager.GetObject("SQLServerProject_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Table_16x {
            get {
                object obj = ResourceManager.GetObject("Table_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Template_16x {
            get {
                object obj = ResourceManager.GetObject("Template_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
